/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.utils;

import lombok.Getter;
import org.bukkit.entity.Player;
import org.bukkit.event.Event;
import org.bukkit.event.HandlerList;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;

public class BauMemberUpdateEvent extends Event {

    @Getter
    private final Set<Player> changed;

    @Getter
    private final Set<Player> newSpectator;

    @Getter
    private final Set<Player> newBuilder;

    public BauMemberUpdateEvent(Set<Player> newSpectator, Set<Player> newBuilder) {
        this.newSpectator = Collections.unmodifiableSet(newSpectator);
        this.newBuilder = Collections.unmodifiableSet(newBuilder);
        Set<Player> changed = new HashSet<>();
        changed.addAll(newSpectator);
        changed.addAll(newBuilder);
        this.changed = Collections.unmodifiableSet(changed);
    }

    private static final HandlerList handlers = new HandlerList();

    public HandlerList getHandlers() {
        return handlers;
    }

    public static HandlerList getHandlerList() {
        return handlers;
    }
}
