/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.misslewars.scripts.implemented;

import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import de.steamwar.misslewars.MissileWars;
import de.steamwar.misslewars.scripts.RunnableScript;
import de.steamwar.misslewars.scripts.RunnableScriptEvent;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

public class CooldownScript implements RunnableScript {

    private int cooldown = 0;

    public CooldownScript(JsonObject object) {
        JsonPrimitive primitive = object.getAsJsonPrimitive("cooldown");
        if(primitive.isNumber()) cooldown = primitive.getAsInt();
    }

    @Override
    public boolean execute(RunnableScriptEvent runnableScriptEvent) {
        Material mainHand = runnableScriptEvent.getPlayer().getInventory().getItemInMainHand().getType();
        Material offHand = runnableScriptEvent.getPlayer().getInventory().getItemInOffHand().getType();
        Bukkit.getScheduler().runTaskLater(MissileWars.getPlugin(), () -> {
            if (mainHand != Material.AIR) runnableScriptEvent.getPlayer().setCooldown(mainHand, cooldown);
            if (offHand != Material.AIR) runnableScriptEvent.getPlayer().setCooldown(offHand, cooldown);
        }, 1);
        return true;
    }
}
