/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.core;

import com.comphenix.tinyprotocol.TinyProtocol;
import de.steamwar.Reflection;
import net.minecraft.network.protocol.game.PacketPlayOutLogin;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.World;

public class WorldIdentifier20 implements WorldIdentifier.IWorldIdentifier {

    private static ResourceKey<World> resourceKey = null;

    private static final Reflection.Field<Integer> playerId = Reflection.getField(PacketPlayOutLogin.class, int.class, 0);
    private static final Class<?> resourceKeyClass = Reflection.getClass("net.minecraft.resources.ResourceKey");
    private static final Class<?> minecraftKeyClass = Reflection.getClass("net.minecraft.resources.MinecraftKey");
    private static final Reflection.Constructor resourceKeyConstructor = Reflection.getConstructor(resourceKeyClass, minecraftKeyClass, minecraftKeyClass);
    private static final Reflection.Constructor minecraftKeyConstructor = Reflection.getConstructor(minecraftKeyClass, String.class, String.class);

    @Override
    public void setResourceKey(String name) {
        resourceKey = (ResourceKey<World>) resourceKeyConstructor.invoke(minecraftKeyConstructor.invoke("minecraft", "dimension"), minecraftKeyConstructor.invoke("steamwar", name));
    }

    public WorldIdentifier20() {
        TinyProtocol.instance.addFilter(PacketPlayOutLogin.class, (player, o) -> {
            if (resourceKey == null) return o;
            PacketPlayOutLogin packet = (PacketPlayOutLogin) o;

            return new PacketPlayOutLogin(
                    playerId.get(packet),
                    packet.c(),
                    packet.d(),
                    packet.e(),
                    packet.f(),
                    packet.g(),
                    packet.h(),
                    resourceKey,
                    packet.j(),
                    packet.k(),
                    packet.l(),
                    packet.m(),
                    packet.n(),
                    packet.o(),
                    packet.p(),
                    packet.q(),
                    packet.r(),
                    packet.s()
            );
        });
    }
}
