/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.util;

import de.steamwar.command.SWCommand;
import de.steamwar.linkage.Linked;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BookMeta;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.List;

@Linked
public class BookReplaceCommand extends SWCommand {

    public BookReplaceCommand() {
        super("bookreplace");
    }

    @Register("color")
    public void color(@Validator Player player) {
        ItemStack itemStack = player.getInventory().getItemInMainHand();
        ItemMeta itemMeta = itemStack.getItemMeta();
        if (itemMeta instanceof BookMeta) {
            BookMeta bookMeta = (BookMeta) itemMeta;
            replace(bookMeta, '&', '§');
            itemStack.setItemMeta(bookMeta);
            player.getInventory().setItemInMainHand(itemStack);
        }
    }

    @Register("uncolor")
    public void uncolor(@Validator Player player) {
        ItemStack itemStack = player.getInventory().getItemInMainHand();
        ItemMeta itemMeta = itemStack.getItemMeta();
        if (itemMeta instanceof BookMeta) {
            BookMeta bookMeta = (BookMeta) itemMeta;
            replace(bookMeta, '§', '&');
            itemStack.setItemMeta(bookMeta);
            player.getInventory().setItemInMainHand(itemStack);
        }
    }

    private void replace(BookMeta bookMeta, char oldChar, char newChar) {
        List<String> stringList = bookMeta.getPages();
        for (int i = 0; i < stringList.size(); i++) {
            bookMeta.setPage(i + 1, stringList.get(i).replace(oldChar, newChar));
        }
    }
}
