/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.misslewars.commands;

import de.steamwar.command.SWCommand;
import de.steamwar.command.TypeValidator;
import de.steamwar.linkage.Linked;
import de.steamwar.misslewars.Config;
import de.steamwar.misslewars.MWTeam;
import de.steamwar.misslewars.MissileWars;
import org.bukkit.GameMode;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

@Linked
public class SpectateCommand extends SWCommand {

    public SpectateCommand() {
        super("spectate", "spec");
    }

    @Register
    public void onCommand(@Validator Player player) {
        MWTeam mwTeam = MissileWars.getTeam(player);
        if (mwTeam == null) return;
        if (mwTeam.size() == 1) {
            player.sendMessage("§cDu bist alleine im Team, zuschauen ist daher nicht möglich.");
        }
        MissileWars.leave(player);
        player.setGameMode(GameMode.SPECTATOR);
        player.getInventory().clear();
        player.updateInventory();
    }

    @ClassValidator(value = Player.class, local = true)
    public TypeValidator<Player> validator() {
        return new TypeValidator<Player>() {
            @Override
            public boolean validate(CommandSender commandSender, Player player, MessageSender messageSender) {
                if (Config.isChallenge()) {
                    messageSender.send("§cDieser Command ist deaktiviert.");
                    return false;
                }
                return true;
            }
        };
    }

    @Override
    protected void sendMessage(CommandSender sender, String message, Object[] args) {
        sender.sendMessage(message);
    }
}
