/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.utils.bossbar;

import de.steamwar.bausystem.region.Region;
import de.steamwar.bausystem.region.RegionSystem;
import org.bukkit.boss.BarColor;
import org.bukkit.boss.BarFlag;
import org.bukkit.boss.BarStyle;
import org.bukkit.boss.BossBar;

public class GlobalBossbar implements BauSystemBossbar {

    private BossBar bossBar;

    public GlobalBossbar(BossBar bossBar) {
        this.bossBar = bossBar;
    }

    @Override
    public String getTitle() {
        return bossBar.getTitle();
    }

    @Override
    public void setTitle(String title) {
        bossBar.setTitle(title);
    }

    @Override
    public double getProgress() {
        return bossBar.getProgress();
    }

    @Override
    public void setProgress(double progress) {
        bossBar.setProgress(progress);
    }

    @Override
    public BarColor getColor() {
        return bossBar.getColor();
    }

    @Override
    public void setColor(BarColor color) {
        bossBar.setColor(color);
    }

    @Override
    public BarStyle getStyle() {
        return bossBar.getStyle();
    }

    @Override
    public void setStyle(BarStyle style) {
        bossBar.setStyle(style);
    }

    @Override
    public boolean hasFlag(BarFlag flag) {
        return bossBar.hasFlag(flag);
    }

    @Override
    public void addFlag(BarFlag flag) {
        bossBar.addFlag(flag);
    }

    @Override
    public void removeFlag(BarFlag flag) {
        bossBar.removeFlag(flag);
    }

    @Override
    public boolean isVisible() {
        return bossBar.isVisible();
    }

    @Override
    public void setVisible(boolean visible) {
        bossBar.setVisible(visible);
    }

    @Override
    public Region getRegion() {
        return RegionSystem.INSTANCE.getGlobalRegion();
    }

    @Override
    public void cleanup() {
        bossBar.removeAll();
        bossBar = null;
    }
}
