/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.core;

import com.mojang.authlib.GameProfile;
import com.mojang.datafixers.util.Pair;
import net.minecraft.network.protocol.game.ClientboundAddEntityPacket;
import net.minecraft.network.protocol.game.ClientboundPlayerInfoRemovePacket;
import net.minecraft.network.protocol.game.ClientboundPlayerInfoUpdatePacket;
import net.minecraft.network.protocol.game.ClientboundSetEquipmentPacket;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.level.GameType;
import org.bukkit.GameMode;

import java.util.Collections;
import java.util.EnumSet;

public class ProtocolWrapper {

    public static final Class<?> itemStack = ItemStack.class;
    public static final Class<?> spawnPacket = ClientboundAddEntityPacket.class;
    public static final Class<?> spawnLivingPacket = ProtocolWrapper.spawnPacket;
    public static final Class<?> equipmentPacket = ClientboundSetEquipmentPacket.class;

    // 0: hand, 1: offhand, 2: feet, 3: legs, 4: chest, 5: head
    public static final EquipmentSlot[] itemSlots = EquipmentSlot.values();

    public static final ProtocolWrapper impl = new ProtocolWrapper();

    public void setEquipmentPacketStack(Object packet, Object slot, Object stack) {
        ClientboundSetEquipmentPacket setEquipmentPacket = (ClientboundSetEquipmentPacket) packet;
        setEquipmentPacket.getSlots().add(Pair.of((EquipmentSlot) slot, (ItemStack) stack));
    }

    public Object playerInfoPacketConstructor(PlayerInfoAction action, GameProfile profile, GameMode mode) {
        if(action == PlayerInfoAction.REMOVE)
            return new ClientboundPlayerInfoRemovePacket(Collections.singletonList(profile.getId()));

        return new ClientboundPlayerInfoUpdatePacket(action == PlayerInfoAction.ADD ?
                EnumSet.of(ClientboundPlayerInfoUpdatePacket.Action.ADD_PLAYER, ClientboundPlayerInfoUpdatePacket.Action.UPDATE_GAME_MODE) : EnumSet.of(ClientboundPlayerInfoUpdatePacket.Action.UPDATE_GAME_MODE),
                Collections.singletonList(new ClientboundPlayerInfoUpdatePacket.Entry(profile.getId(), profile, false, 0, GameType.byId(mode.getValue()), null, false, 0, null)));
    }

    public enum PlayerInfoAction {
        ADD,
        GAMEMODE,
        REMOVE
    }
}
