/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.schematicsystem;

import de.steamwar.linkage.AbstractLinker;
import de.steamwar.linkage.SpigotLinker;
import de.steamwar.message.Message;
import de.steamwar.sql.GameModeConfig;
import de.steamwar.sql.SchematicType;
import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.plugin.java.JavaPlugin;

public class SchematicSystem extends JavaPlugin {
    public static final Message MESSAGE = new Message("SchematicSystem", SchematicSystem.class.getClassLoader());

    private static SchematicSystem instance;

    public static GameModeConfig<Material, String> getGameModeConfig(SchematicType type) {
        GameModeConfig<Material, String> gameModeConfig = GameModeConfig.getBySchematicType(type);
        if (gameModeConfig == null) return null;
        if (gameModeConfig.CheckQuestions.isEmpty() && gameModeConfig.Schematic.ManualCheck) return null;
        return gameModeConfig;
    }

    @Override
    public void onEnable() {
        instance = this;

        SpigotLinker spigotLinker = new SpigotLinker(this, MESSAGE);
        try {
            spigotLinker.link();
        } catch (AbstractLinker.LinkException e) {
            e.printStackTrace();
            Bukkit.shutdown();
        }
    }

    public static SchematicSystem getInstance() {
        return instance;
    }
}
