/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.script;

import de.steamwar.sql.Script;
import de.steamwar.sql.SteamwarUser;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BookMeta;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

public class ScriptHelper {

    private static final String PAGE_SEPARATOR = "\n\0\n";

    public static ItemStack getScriptItem(Script script, boolean writeable) {
        ItemStack itemStack = new ItemStack(writeable ? Material.WRITABLE_BOOK : Material.WRITTEN_BOOK);
        BookMeta meta = (BookMeta) itemStack.getItemMeta();
        if (!writeable) {
            meta.setTitle(script.getName());
            meta.setAuthor(SteamwarUser.byId(script.getUserId()).getUserName());
        }
        meta.setPages(getScriptPages(script));
        itemStack.setItemMeta(meta);
        return itemStack;
    }

    public static List<String> getScriptPages(Script script) {
        return Arrays.stream(script.getCode().split(PAGE_SEPARATOR)).collect(Collectors.toList());
    }

    public static String getScriptString(List<String> pages) {
        return String.join(PAGE_SEPARATOR, pages);
    }
}
