/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.region;

import com.sk89q.worldedit.math.BlockVector3;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.ToString;
import org.bukkit.Location;
import org.bukkit.World;
import org.bukkit.entity.Player;

@Getter
@ToString
@EqualsAndHashCode
@AllArgsConstructor
public class Point {

    public static final Point ZERO = new Point(0, 0, 0);

    private final int x;
    private final int y;
    private final int z;

    public static Point fromLocation(final Location location) {
        return new Point(location.getBlockX(), location.getBlockY(), location.getBlockZ());
    }

    public static Point fromBlockVector3(final BlockVector3 blockVector3) {
        return new Point(blockVector3.getBlockX(), blockVector3.getBlockY(), blockVector3.getBlockZ());
    }

    public Point add(int x, int y, int z) {
        return new Point(this.x + x, this.y + y, this.z + z);
    }

    public Point subtract(int x, int y, int z) {
        return new Point(this.x - x, this.y - y, this.z - z);
    }

    public Point divide(int factor) {
        return new Point(x / factor, y / factor, z / factor);
    }

    public Location toLocation(World world) {
        return new Location(world, x, y, z);
    }

    public Location toLocation(World world, double dx, double dy, double dz) {
        return new Location(world, x + dx, y + dy, z + dz);
    }

    public Location toLocation(Player player) {
        return new Location(player.getWorld(), x, y, z, player.getLocation().getYaw(), player.getLocation().getPitch());
    }

    public Location toLocation(Player player, double dx, double dy, double dz) {
        return new Location(player.getWorld(), x + dx, y + dy, z + dz, player.getLocation().getYaw(), player.getLocation().getPitch());
    }

    public BlockVector3 toBlockVector3() {
        return BlockVector3.at(this.x, this.y, this.z);
    }
}