/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.utils;

import com.destroystokyo.paper.event.server.ServerTickEndEvent;
import com.destroystokyo.paper.event.server.ServerTickStartEvent;
import de.steamwar.bausystem.BauSystem;
import org.bukkit.Bukkit;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;

public class TickListener19 implements TickListener, Listener {

    private boolean tickStartRan = false;

    public TickListener19() {
        Bukkit.getPluginManager().registerEvents(this, BauSystem.getInstance());
    }

    @EventHandler
    public void onServerTickStart(ServerTickStartEvent event) {
        if (TickManager.impl.isFrozen()) return;
        Bukkit.getPluginManager().callEvent(new TickStartEvent());
        tickStartRan = true;
    }

    @EventHandler
    public void onServerTickEnd(ServerTickEndEvent event) {
        if (!tickStartRan) return;
        Bukkit.getPluginManager().callEvent(new TickEndEvent());
        tickStartRan = false;
    }
}
