/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.linkage;

import de.steamwar.command.SWCommand;
import de.steamwar.message.Message;
import de.steamwar.network.packets.PacketHandler;
import lombok.NonNull;
import org.bukkit.Bukkit;
import org.bukkit.event.HandlerList;
import org.bukkit.event.Listener;
import org.bukkit.plugin.java.JavaPlugin;

public class SpigotLinker extends AbstractLinker<JavaPlugin> {

    private final Message message;

    public SpigotLinker(@NonNull JavaPlugin plugin, Message message) {
        super(plugin);
        this.message = message;
    }

    @Override
    protected boolean pluginCheck(@NonNull Class<?> clazz, PluginCheck pluginCheck) {
        if (pluginCheck.has() == PluginCheck.Has.THIS && Bukkit.getPluginManager().getPlugin(pluginCheck.value()) != null) {
            return true;
        }
        if (pluginCheck.has() == PluginCheck.Has.NOT && Bukkit.getPluginManager().getPlugin(pluginCheck.value()) == null) {
            return true;
        }
        return false;
    }

    @Override
    protected void linkObject(Object any) {
        if (any instanceof SWCommand) {
            ((SWCommand) any).setMessage(message);
        }
        if (any instanceof Listener) {
            Bukkit.getPluginManager().registerEvents((Listener) any, plugin);
        }
        if (any instanceof PacketHandler) {
            ((PacketHandler) any).register();
        }
    }

    @Override
    protected void unlinkObject(Object any) {
        if (any instanceof Listener) {
            HandlerList.unregisterAll((Listener) any);
        }
    }
}
