/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.util;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.command.SWCommand;
import de.steamwar.linkage.Linked;
import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.bukkit.event.player.PlayerTeleportEvent;

import java.util.Random;

@Linked
public class TeleportCommand extends SWCommand {

    private static final Random RAND = new Random();

    public TeleportCommand() {
        super("teleport", "tp");
    }

    @Register(description = "OTHER_TELEPORT_HELP")
    public void genericCommand(Player p, Player target) {
        if (p.getUniqueId().equals(target.getUniqueId())) {
            BauSystem.MESSAGE.send("OTHER_TELEPORT_SELF_" + RAND.nextInt(5), p);
            return;
        }
        p.teleport(target, PlayerTeleportEvent.TeleportCause.COMMAND);
    }

    @Register
    public void locationCommand(Player p, int x, int y, int z) {
        Location l = p.getLocation();
        l.setX(x + 0.5);
        l.setY(y);
        l.setZ(z + 0.5);
        p.teleport(l, PlayerTeleportEvent.TeleportCause.COMMAND);
    }

    @Register
    public void locationCommand(Player p, double x, double y, double z) {
        Location l = p.getLocation();
        l.setX(x);
        l.setY(y);
        l.setZ(z);
        p.teleport(l, PlayerTeleportEvent.TeleportCause.COMMAND);
    }
}