/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.loadtimer;

import de.steamwar.bausystem.region.Region;
import de.steamwar.linkage.Linked;
import org.bukkit.Material;
import org.bukkit.entity.EntityType;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.block.BlockPlaceEvent;
import org.bukkit.event.entity.EntityExplodeEvent;
import org.bukkit.event.entity.EntitySpawnEvent;
import org.bukkit.event.player.PlayerInteractEvent;

import static de.steamwar.bausystem.features.loadtimer.Loadtimer.*;

@Linked
public class LoadtimerListener implements Listener {

    @EventHandler
    public void onBlockPlace(BlockPlaceEvent event) {
        if (!getTimers().isEmpty() && event.getBlockPlaced().getType() == Material.TNT) {
            Region r = Region.getRegion(event.getBlock().getLocation());
            if (hasTimer(r)) {
                getTimer(r).onTntPlace(event);
            }
        }
    }

    @EventHandler
    public void onPlayerInteract(PlayerInteractEvent event) {
        if (!getTimers().isEmpty()) {
            Region r = Region.getRegion(event.getPlayer().getLocation());
            if (hasTimer(r)) {
                getTimer(r).onInteract(event);
            }
        }
    }

    @EventHandler
    public void onEntitySpawn(EntitySpawnEvent event) {
        if (!getTimers().isEmpty() && event.getEntityType() == EntityType.TNT) {
            Region r = Region.getRegion(event.getLocation());
            if (hasTimer(r)) {
                getTimer(r).onTntSpawn();
            }
        }
    }

    @EventHandler
    public void onEntityExplode(EntityExplodeEvent event) {
        if (!getTimers().isEmpty() && event.getEntityType() == EntityType.TNT) {
            Region r = Region.getRegion(event.getLocation());
            if (hasTimer(r)) {
                getTimer(r).onTntExplode(event);
            }
        }
    }
}
