/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.entity;

import net.minecraft.network.protocol.game.ClientboundAddEntityPacket;
import net.minecraft.network.protocol.game.ClientboundTeleportEntityPacket;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.PositionMoveRotation;
import net.minecraft.world.phys.Vec3;

import java.util.Collections;

public class PacketConstructor {
    public static final PacketConstructor impl = new PacketConstructor();

    public Object teleportPacket(int entityId, double x, double y, double z, float yaw, float pitch) {
        PositionMoveRotation rot = new PositionMoveRotation(new Vec3(x, y, z), Vec3.ZERO, pitch, yaw);
        return new ClientboundTeleportEntityPacket(entityId, rot, Collections.emptySet(), false);
    }

    public Object createRPlayerSpawn(RPlayer player) {
        return new ClientboundAddEntityPacket(
                player.entityId,
                player.uuid,
                player.x,
                player.y,
                player.z,
                player.yaw,
                player.pitch,
                EntityType.PLAYER,
                0,
                Vec3.ZERO,
                player.headYaw
        );
    }
}
