/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.util;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.SWUtils;
import de.steamwar.bausystem.region.Region;
import de.steamwar.bausystem.region.RegionUtils;
import de.steamwar.command.SWCommand;
import de.steamwar.linkage.Linked;
import org.bukkit.Bukkit;
import org.bukkit.World;
import org.bukkit.entity.Player;

import java.util.concurrent.atomic.AtomicLong;

@Linked
public class KillAllCommand extends SWCommand {

    private static final World WORLD = Bukkit.getWorlds().get(0);

    public KillAllCommand() {
        super("killall", "removeall");
    }

    @Register(description = "OTHER_KILLALL_HELP_SELF")
    public void genericCommand(@Validator Player player) {
        genericCommand(player, RegionSelectionType.LOCAL);
    }

    @Register(description = "OTHER_KILLALL_HELP_ALL")
    public void genericCommand(@Validator Player player, RegionSelectionType regionSelectionType) {
        Region region = Region.getRegion(player.getLocation());
        AtomicLong count = new AtomicLong(0);
        if (regionSelectionType == RegionSelectionType.GLOBAL || region.getType().isGlobal()) {
            WORLD.getEntities()
                    .stream()
                    .filter(e -> !(e instanceof Player))
                    .forEach(entity -> {
                        entity.remove();
                        count.incrementAndGet();
                    });
            SWUtils.actionBar(current -> BauSystem.MESSAGE.parse("OTHER_KILLALL_GLOBAL", current, count.get()));
        } else {
            WORLD.getEntities()
                    .stream()
                    .filter(e -> !(e instanceof Player))
                    .filter(e -> region.getArea().inRegion(e.getLocation(), false))
                    .forEach(entity -> {
                        entity.remove();
                        count.incrementAndGet();
                    });
            RegionUtils.actionBar(region, "OTHER_KILLALL_REGION", count.get());
        }
    }
}
