/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.fightsystem.record;

import de.steamwar.fightsystem.Config;
import de.steamwar.fightsystem.FightSystem;
import org.bukkit.Bukkit;

import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.logging.Level;

public class LiveServer {

    private final ServerSocket socket;

    public LiveServer() throws IOException {
        socket = new ServerSocket(Config.SpectatePort);
        Bukkit.getScheduler().runTaskAsynchronously(FightSystem.getPlugin(), this::acceptConnections);
    }

    public void close() {
        try {
            socket.close();
        } catch (IOException e) {
            Bukkit.getLogger().log(Level.SEVERE, "Could not close socket", e);
        }
    }

    private void acceptConnections() {
        try {
            while (!socket.isClosed()) {
                Socket s = socket.accept();
                if (PacketProcessor.isReplaying()) {
                    s.close();
                } else {
                    new LiveSource(s);
                }
            }
        } catch (IOException e) {
            Bukkit.getLogger().log(Level.INFO, "Stopping accepting connections", e);
        }
    }
}
