/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.fightsystem.utils;

import com.comphenix.tinyprotocol.TinyProtocol;
import com.mojang.authlib.GameProfile;
import de.steamwar.core.ProtocolWrapper;
import de.steamwar.fightsystem.FightSystem;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.state.BlockState;
import org.bukkit.GameMode;
import org.bukkit.Material;
import org.bukkit.World;
import org.bukkit.block.Block;
import org.bukkit.craftbukkit.CraftWorld;
import org.bukkit.craftbukkit.block.CraftBlockState;
import org.bukkit.craftbukkit.util.CraftMagicNumbers;
import org.bukkit.entity.Entity;
import org.bukkit.entity.Player;

public class BlockIdWrapper {
    public static final BlockIdWrapper impl = new BlockIdWrapper();

    public Material idToMaterial(int blockState) {
        return CraftMagicNumbers.getMaterial(net.minecraft.world.level.block.Block.stateById(blockState)).getItemType();
    }

    public int blockToId(Block block) {
        return net.minecraft.world.level.block.Block.getId(((CraftBlockState) block.getState()).getHandle());
    }

    public void setBlock(World world, int x, int y, int z, int blockState) {
        BlockState blockData = net.minecraft.world.level.block.Block.stateById(blockState);
        ServerLevel level = ((CraftWorld) world).getHandle();
        BlockPos pos = new BlockPos(x, y, z);

        level.removeBlockEntity(pos);
        level.setBlock(pos, blockData, blockState);
        level.getChunkSource().blockChanged(pos);
    }

    public void trackEntity(Player player, Entity entity) {
        if (entity instanceof Player) {
            TinyProtocol.instance.sendPacket(player, ProtocolWrapper.playerInfoPacketConstructor(ProtocolWrapper.PlayerInfoAction.REMOVE, new GameProfile(entity.getUniqueId(), entity.getName()), GameMode.CREATIVE));
        }

        player.showEntity(FightSystem.getPlugin(), entity);
    }

    public void untrackEntity(Player player, Entity entity) {
        player.hideEntity(FightSystem.getPlugin(), entity);

        if (entity instanceof Player) {
            TinyProtocol.instance.sendPacket(player, ProtocolWrapper.playerInfoPacketConstructor(ProtocolWrapper.PlayerInfoAction.ADD, new GameProfile(entity.getUniqueId(), entity.getName()), GameMode.CREATIVE));
        }
    }
}
