/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.simulator.execute;

import de.steamwar.bausystem.features.simulator.data.Simulator;
import de.steamwar.bausystem.features.simulator.data.tnt.TNTElement;
import de.steamwar.bausystem.region.Region;
import de.steamwar.bausystem.utils.bossbar.BossBarService;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;

public class SimulatorStabGenerator {

    private final StabData stabData;

    public SimulatorStabGenerator(Region region, Simulator simulator, TNTElement tntElement, int depthLimit) {
        stabData = new StabData(region, simulator, tntElement, tntElement.getPhases(), depthLimit);
        new StabSetup(stabData);
    }

    public void cancel() {
        stabData.cancel = true;
        stabData.simulator.setStabGenerator(null);
        for (Player player : Bukkit.getOnlinePlayers()) {
            BossBarService.instance.remove(player, stabData.region, "simulator_stab_generator");
        }
    }
}
