/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.world;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.bausystem.Permission;
import de.steamwar.bausystem.SWUtils;
import de.steamwar.command.SWCommand;
import de.steamwar.command.TypeValidator;
import de.steamwar.linkage.Linked;
import de.steamwar.sql.SteamwarUser;
import de.steamwar.sql.UserPerm;
import org.bukkit.Bukkit;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

@Linked
public class StopCommand extends SWCommand {

    public StopCommand() {
        super("stop");
    }

    @Register(description = "STOP_HELP")
    public void genericCommand(@Validator CommandSender sender) {
        SWUtils.message(current -> BauSystem.MESSAGE.parsePrefixed("STOP_MESSAGE", current));
        Bukkit.getServer().shutdown();
    }

    @ClassValidator(value = CommandSender.class, local = true)
    public TypeValidator<CommandSender> validator() {
        return (commandSender, sender, messageSender) -> {
            if (!(sender instanceof Player)) {
                return true;
            }
            Player player = (Player) sender;
            if (Permission.SUPERVISOR.hasPermission(player)) {
                return true;
            }
            SteamwarUser user = SteamwarUser.get(player.getUniqueId());
            if (user.hasPerm(UserPerm.ADMINISTRATION)) {
                return true;
            }
            messageSender.send("NO_PERMISSION");
            return false;
        };
    }
}
