/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.util;

import de.steamwar.bausystem.BauSystem;
import de.steamwar.command.SWCommand;
import de.steamwar.linkage.Linked;
import org.bukkit.Material;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

@Linked
public class ClearCommand extends SWCommand {

    public ClearCommand() {
        super("clear");
    }

    @Register(description = "OTHER_CLEAR_HELP_SELF")
    public void genericClearCommand(Player p) {
        clear(p);
        BauSystem.MESSAGE.send("OTHER_CLEAR_CLEARED", p);
    }

    @Register(description = "OTHER_CLEAR_HELP_PLAYER")
    public void clearPlayerCommand(@Validator Player p, Player target) {
        clear(target);
        BauSystem.MESSAGE.send("OTHER_CLEAR_FROM", target, p.getName());
        BauSystem.MESSAGE.send("OTHER_CLEAR_TO", p, target.getName());
    }

    private void clear(Player player) {
        player.getInventory().clear();
        player.getInventory().setHelmet(new ItemStack(Material.AIR));
        player.getInventory().setChestplate(new ItemStack(Material.AIR));
        player.getInventory().setLeggings(new ItemStack(Material.AIR));
        player.getInventory().setBoots(new ItemStack(Material.AIR));
    }
}
