/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.misslewars.countdowns;

import de.steamwar.linkage.Linked;
import de.steamwar.misslewars.Config;
import de.steamwar.misslewars.FightState;
import de.steamwar.misslewars.MissileWars;
import de.steamwar.misslewars.StateDependent;
import de.steamwar.misslewars.items.SpecialItem;
import org.bukkit.Bukkit;
import org.bukkit.inventory.ItemStack;
import org.bukkit.scheduler.BukkitTask;

import java.util.EnumSet;

@Linked
public class ItemCountdown extends StateDependent {

    private BukkitTask task;
    private int lastTime = 0;
    private int currenTime = 0;

    public ItemCountdown() {
        super(EnumSet.of(FightState.FIGHTING));
    }

    private void run() {
        currenTime++;

        int teamCount = Math.max(MissileWars.getBlueTeam().size(), MissileWars.getRedTeam().size());
        if (teamCount == 0) return;
        int timeDelay = Config.ItemTime / teamCount;

        if (lastTime + timeDelay < currenTime) {
            lastTime = currenTime;

            ItemStack itemStack = SpecialItem.getRandomItem();
            MissileWars.getBlueTeam().givePlayerItem(itemStack);
            MissileWars.getRedTeam().givePlayerItem(itemStack);
        }

        MissileWars.getBlueTeam().countdown(timeDelay, currenTime - lastTime);
        MissileWars.getRedTeam().countdown(timeDelay, currenTime - lastTime);
    }

    @Override
    public void enable() {
        task = Bukkit.getScheduler().runTaskTimer(MissileWars.getPlugin(), this::run, 0, 1);
    }

    @Override
    public void disable() {
        if (task != null && !task.isCancelled()) task.cancel();
    }
}
