/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.core;

import de.steamwar.network.packets.PacketHandler;
import de.steamwar.network.packets.server.ClientVersionPacket;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerQuitEvent;

import java.util.HashMap;
import java.util.Map;
import java.util.UUID;

public class PlayerVersion extends PacketHandler implements Listener {

    private static final Map<UUID, Integer> playerVersions = new HashMap<>();

    public static int getVersion(Player player) {
        return playerVersions.getOrDefault(player.getUniqueId(), -1);
    }

    public static boolean isBedrock(Player player) {
        return player.getName().startsWith(".");
    }

    public PlayerVersion() {
        Bukkit.getPluginManager().registerEvents(this, Core.getInstance());
        register();
    }

    @Handler
    public void handlePacket(ClientVersionPacket clientVersionPacket) {
        playerVersions.put(clientVersionPacket.getPlayer(), clientVersionPacket.getVersion());
    }

    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    public void onPlayerQuit(PlayerQuitEvent event) {
        playerVersions.remove(event.getPlayer().getUniqueId());
    }
}
