/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.misslewars.listener;

import de.steamwar.linkage.Linked;
import de.steamwar.misslewars.FightState;
import de.steamwar.misslewars.MissileWars;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.entity.EntityDamageByEntityEvent;

import java.util.EnumSet;

@Linked
public class FightListener extends BasicListener {

	public FightListener() {
		super(EnumSet.of(FightState.FIGHTING));
	}

	@EventHandler
	public void onDamage(EntityDamageByEntityEvent e){
		if(!(e.getDamager() instanceof Player && e.getEntity() instanceof Player))
			return;

		Player damager = (Player)e.getDamager();
		Player reciever = (Player)e.getEntity();

		if(MissileWars.getTeam(damager) == MissileWars.getTeam(reciever))
			e.setCancelled(true);
	}
}
