/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.region;

import de.steamwar.bausystem.BauSystem;
import lombok.experimental.UtilityClass;
import net.md_5.bungee.api.ChatMessageType;
import net.md_5.bungee.api.chat.TextComponent;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;

import java.util.function.Consumer;
import java.util.function.Function;

@UtilityClass
public class RegionUtils {

    public void actionBar(Region region, String s, Object... objects) {
        forEachInRegion(region, player -> {
            player.spigot().sendMessage(ChatMessageType.ACTION_BAR, TextComponent.fromLegacyText(BauSystem.MESSAGE.parse(s, player, objects)));
        });
    }

    public void message(Region region, String s, Object... objects) {
        forEachInRegion(region, player -> BauSystem.MESSAGE.send(s, player, objects));
    }

    public void message(Region region, Function<Player, String> function) {
        forEachInRegion(region, player -> {
            String message = function.apply(player);
            if (message == null) {
                return;
            }

            player.sendMessage(message);
        });
    }

    public void message(Region region, Consumer<Player> consumer) {
        forEachInRegion(region, consumer);
    }

    public void forEachInRegion(Region region, Consumer<Player> consumer) {
        Bukkit.getOnlinePlayers()
                .stream()
                .filter(player -> region.getArea().inRegion(player.getLocation(), false))
                .filter(player -> !region.getType().isGlobal() || Region.getRegion(player.getLocation()).getType().isGlobal())
                .forEach(consumer);
    }
}
