/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.fightsystem.utils;

import io.papermc.paper.datacomponent.DataComponentType;
import io.papermc.paper.datacomponent.DataComponentTypes;
import org.bukkit.Location;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import java.util.HashSet;
import java.util.Set;

public class ReflectionWrapper {
    public static final ReflectionWrapper impl = new ReflectionWrapper();

    private static final Set<DataComponentType> FORBIDDEN_TYPES = new HashSet<>();

    static {
        FORBIDDEN_TYPES.add(DataComponentTypes.CUSTOM_NAME);
        FORBIDDEN_TYPES.add(DataComponentTypes.PROFILE);
        FORBIDDEN_TYPES.add(DataComponentTypes.UNBREAKABLE);
        FORBIDDEN_TYPES.add(DataComponentTypes.BLOCK_DATA);
        FORBIDDEN_TYPES.add(DataComponentTypes.BLOCKS_ATTACKS);
        FORBIDDEN_TYPES.add(DataComponentTypes.BUNDLE_CONTENTS);
        FORBIDDEN_TYPES.add(DataComponentTypes.CUSTOM_MODEL_DATA);

        FORBIDDEN_TYPES.add(DataComponentTypes.ATTRIBUTE_MODIFIERS);
        FORBIDDEN_TYPES.add(DataComponentTypes.TOOL);
        FORBIDDEN_TYPES.add(DataComponentTypes.WEAPON);
        FORBIDDEN_TYPES.add(DataComponentTypes.FOOD);
        FORBIDDEN_TYPES.add(DataComponentTypes.CONSUMABLE);
        FORBIDDEN_TYPES.add(DataComponentTypes.POTION_CONTENTS);
        FORBIDDEN_TYPES.add(DataComponentTypes.STORED_ENCHANTMENTS);
        FORBIDDEN_TYPES.add(DataComponentTypes.CAN_BREAK);
        FORBIDDEN_TYPES.add(DataComponentTypes.CAN_PLACE_ON);
        FORBIDDEN_TYPES.add(DataComponentTypes.MAX_DAMAGE);
        FORBIDDEN_TYPES.add(DataComponentTypes.USE_REMAINDER);
        FORBIDDEN_TYPES.add(DataComponentTypes.USE_COOLDOWN);
        FORBIDDEN_TYPES.add(DataComponentTypes.SUSPICIOUS_STEW_EFFECTS);
        FORBIDDEN_TYPES.add(DataComponentTypes.CHARGED_PROJECTILES);
        FORBIDDEN_TYPES.add(DataComponentTypes.INTANGIBLE_PROJECTILE);
        FORBIDDEN_TYPES.add(DataComponentTypes.FIREWORKS);
        FORBIDDEN_TYPES.add(DataComponentTypes.FIREWORK_EXPLOSION);
        FORBIDDEN_TYPES.add(DataComponentTypes.EQUIPPABLE);
        FORBIDDEN_TYPES.add(DataComponentTypes.REPAIR_COST);
        FORBIDDEN_TYPES.add(DataComponentTypes.ENCHANTABLE);
    }

    public Object explosionHider(Player player, Object packet, PacketHiderFunction packetHiderFunction) {
        return packet;
    }

    public boolean hasItems(ItemStack stack) {
        FORBIDDEN_TYPES.forEach(stack::resetData);
        return false;
    }

    public interface PacketHiderFunction {
        Object hide(Player player, Object packet, Location location);
    }
}
