/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.lobby.particle.elements;

import de.steamwar.lobby.LobbySystem;
import de.steamwar.lobby.particle.ParticleElement;
import de.steamwar.lobby.particle.ParticleEnum;
import de.steamwar.lobby.particle.ParticleTickData;
import org.bukkit.Bukkit;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;

import java.util.HashMap;
import java.util.Map;
import java.util.Random;

public class RandomParticle implements ParticleElement {

    private RandomData randomData;
    private ParticleEnum[] particleEnums;

    private static class RandomData implements Listener {
        private Random random = new Random();
        private int max;
        private Map<Player, Integer> data = new HashMap<>();

        public RandomData(int max) {
            this.max = max;
        }

        @EventHandler(ignoreCancelled = true)
        public void onPlayerJoin(PlayerJoinEvent event) {
            data.put(event.getPlayer(), random.nextInt(max));
        }

        @EventHandler(ignoreCancelled = true)
        public void onPlayerQuit(PlayerQuitEvent event) {
            data.remove(event.getPlayer());
        }
    }

    public RandomParticle(ParticleEnum... particleEnums) {
        if (particleEnums.length == 0) {
            throw new IllegalArgumentException("ParticleEnums must not be empty");
        }
        this.randomData = new RandomData(particleEnums.length);
        Bukkit.getPluginManager().registerEvents(randomData, LobbySystem.getInstance());
        this.particleEnums = particleEnums;
    }

    @Override
    public void tick(ParticleTickData particleTickData) {
        int currentNumber = randomData.data.getOrDefault(particleTickData.getPlayer(), 0);
        particleEnums[currentNumber].getParticle().getParticleElement().tick(particleTickData);
    }
}
