/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.core;

import com.comphenix.tinyprotocol.TinyProtocol;
import de.steamwar.Reflection;
import net.minecraft.network.protocol.game.ClientboundLoginPacket;
import net.minecraft.network.protocol.game.CommonPlayerSpawnInfo;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.level.Level;

public class WorldIdentifier21 implements WorldIdentifier.IWorldIdentifier {

    private static ResourceKey<Level> resourceKey = null;

    private static final Class<?> resourceKeyClass = Reflection.getClass("net.minecraft.resources.ResourceKey");
    private static final Class<?> minecraftKeyClass = Reflection.getClass("net.minecraft.resources.MinecraftKey");
    private static final Reflection.Constructor resourceKeyConstructor = Reflection.getConstructor(resourceKeyClass, minecraftKeyClass, minecraftKeyClass);
    private static final Reflection.Constructor minecraftKeyConstructor = Reflection.getConstructor(minecraftKeyClass, String.class, String.class);

    @Override
    public void setResourceKey(String name) {
        resourceKey = (ResourceKey<Level>) resourceKeyConstructor.invoke(minecraftKeyConstructor.invoke("minecraft", "dimension"), minecraftKeyConstructor.invoke("steamwar", name));
    }

    public WorldIdentifier21() {
        TinyProtocol.instance.addFilter(ClientboundLoginPacket.class, (player, o) -> {
            if (resourceKey == null) return o;
            ClientboundLoginPacket packet = (ClientboundLoginPacket) o;

            return new ClientboundLoginPacket(packet.playerId(),
                    packet.hardcore(),
                    packet.levels(),
                    packet.maxPlayers(),
                    packet.chunkRadius(),
                    packet.simulationDistance(),
                    packet.reducedDebugInfo(),
                    packet.showDeathScreen(),
                    packet.doLimitedCrafting(),
                    new CommonPlayerSpawnInfo(
                            packet.commonPlayerSpawnInfo().dimensionType(),
                            resourceKey,
                            packet.commonPlayerSpawnInfo().seed(),
                            packet.commonPlayerSpawnInfo().gameType(),
                            packet.commonPlayerSpawnInfo().previousGameType(),
                            packet.commonPlayerSpawnInfo().isDebug(),
                            packet.commonPlayerSpawnInfo().isFlat(),
                            packet.commonPlayerSpawnInfo().lastDeathLocation(),
                            packet.commonPlayerSpawnInfo().portalCooldown(),
                            packet.commonPlayerSpawnInfo().seaLevel()
                    ),
                    packet.enforcesSecureChat()
            );
        });
    }
}
