/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.features.slaves.panzern.algorithms;

import de.steamwar.bausystem.features.slaves.panzern.PanzernAlgorithm;
import de.steamwar.bausystem.features.slaves.panzern.PanzernResult;
import de.steamwar.bausystem.utils.FlatteningWrapper;
import de.steamwar.linkage.Linked;
import org.bukkit.Material;
import org.bukkit.block.Block;
import org.bukkit.block.BlockFace;
import org.bukkit.block.data.BlockData;
import org.bukkit.block.data.type.Piston;

import java.util.Map;
import java.util.Set;

@Linked
public class PistonLine implements PanzernAlgorithm {

    @Override
    public PanzernResult check(Block source, Map<BlockFace, Block> adjacent, Set<Material> adjacentMaterials) {
        for (BlockFace blockFace : BLOCK_FACES) {
            for (int i = 1; i < 14; i++) {
                Block relativeBlock = source.getRelative(blockFace.getModX() * i, blockFace.getModY() * i, blockFace.getModZ() * i);
                if (relativeBlock.getType().isAir()) {
                    break;
                }
                BlockData blockData = relativeBlock.getBlockData();
                if (!(blockData instanceof Piston)) {
                    if (FlatteningWrapper.impl.isUnpusheable(relativeBlock.getType())) {
                        break;
                    }
                    if (FlatteningWrapper.impl.isBreakingOnPush(relativeBlock.getType())) {
                        break;
                    }
                    continue;
                }
                Piston piston = (Piston) blockData;
                if (piston.getFacing() == blockFace.getOppositeFace()) {
                    return PanzernResult.EMPTY;
                }
            }
        }
        return PanzernResult.DEFAULT;
    }
}
