/*
 *   This file is a part of the SteamWar software.
 *
 *   Copyright (C) 2025 SteamWar.de-Serverteam
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU Affero General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU Affero General Public License for more details.
 *
 *   You should have received a copy of the GNU Affero General Public License
 *   along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package de.steamwar.bausystem.utils.bossbar;

import de.steamwar.bausystem.region.Region;
import de.steamwar.linkage.Linked;
import org.bukkit.Bukkit;
import org.bukkit.boss.BarColor;
import org.bukkit.boss.BarStyle;
import org.bukkit.boss.BossBar;
import org.bukkit.entity.Player;
import org.bukkit.event.EventHandler;
import org.bukkit.event.EventPriority;
import org.bukkit.event.Listener;
import org.bukkit.event.player.PlayerQuitEvent;

import java.util.HashMap;
import java.util.Map;

@Linked
public class BossBarService implements Listener {

    public static BossBarService instance;

    public BossBarService() {
        instance = this;
    }

    private final Map<Player, Map<Region, Map<String, BauSystemBossbar>>> playerBossBars = new HashMap<>();

    public synchronized BauSystemBossbar get(Player player, Region region, String key) {
        return playerBossBars.computeIfAbsent(player, p -> new HashMap<>())
                .computeIfAbsent(region, r -> new HashMap<>())
                .computeIfAbsent(key, k -> {
                    BossBar bossBar = Bukkit.createBossBar("", BarColor.WHITE, BarStyle.SOLID);
                    bossBar.addPlayer(player);
                    if (region.getType().isGlobal()) {
                        return new GlobalBossbar(bossBar);
                    } else {
                        return new RegionedBossbar(bossBar, region, player);
                    }
                });
    }

    public synchronized void removeAll(Player player, String key) {
        Map<Region, Map<String, BauSystemBossbar>> regionMap = playerBossBars.get(player);
        if (regionMap == null) return;
        for (Map<String, BauSystemBossbar> bossBarMap : regionMap.values()) {
            BauSystemBossbar bossBar = bossBarMap.remove(key);
            if (bossBar == null) continue;
            bossBar.cleanup();
        }
    }

    public synchronized void removeAll(Player player) {
        Map<Region, Map<String, BauSystemBossbar>> regionMap = playerBossBars.remove(player);
        if (regionMap == null) return;
        for (Map<String, BauSystemBossbar> bossBarMap : regionMap.values()) {
            for (BauSystemBossbar bossBar : bossBarMap.values()) {
                bossBar.cleanup();
            }
        }
    }

    public synchronized void remove(Player player, Region region, String key) {
        Map<Region, Map<String, BauSystemBossbar>> regionMap = playerBossBars.get(player);
        if (regionMap == null) return;
        Map<String, BauSystemBossbar> bossBarMap = regionMap.get(region);
        if (bossBarMap == null) return;
        BauSystemBossbar bossBar = bossBarMap.remove(key);
        if (bossBar == null) return;
        bossBar.cleanup();
    }

    @EventHandler(ignoreCancelled = true, priority = EventPriority.MONITOR)
    public void onPlayerQuit(PlayerQuitEvent event) {
        removeAll(event.getPlayer());
    }
}
